engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
    config: .coffeelint.json
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
  shellcheck:
    enabled: true


ratings:
  paths:
  - Gemfile.lock
  - app/**
  - lib/**
  - "**.js"
  - "**.rb"


exclude_paths:
  - bin/**/*
  - doc/**/*
  - spec/**/*
  - test/**/*
  - vendor/**/*
