.deploy: &deploy
  before_script:
    - cat /etc/os-release
    - uname -a
    - ruby --version
    - gem --version
    - bundle --version
    - apk add --no-cache --update git
    - bundle install --clean --deployment --jobs=2 --without default development lint production test
  image: ruby:alpine
  only:
    - master
  stage: deploy
  tags:
    - 2gb

.lint: &lint
  before_script:
    - cat /etc/os-release
    - uname -a
    - ruby --version
    - gem --version
    - bundle --version
    - apk add --no-cache --update git
    - bundle install --clean --deployment --jobs=2 --without default deployment development production test
  image: ruby:alpine
  stage: lint
  tags:
    - 2gb

.test: &test
  artifacts:
    expire_in: 1 day
    paths:
      - coverage
  script:
    - bundle install --clean --deployment --jobs=$(nproc) --without deployment development lint production
    - bin/rake
  stage: test
  tags:
    - 2gb

.use_jruby: &use_jruby
  <<: *test
  before_script:
    - cat /etc/os-release
    - uname -a
    - ruby --version
    - gem --version
    - bundle --version
    - apt-get -qq update
    - apt-get -qq install git texlive-xetex uuid-runtime
  image: jruby:9.1

.use_mri: &use_mri
  <<: *test
  before_script:
    - cat /etc/os-release
    - uname -a
    - ruby --version
    - gem --version
    - bundle --version
    - apt-get -qq update
    - apt-get -qq install texlive-xetex uuid-runtime

cache:
  paths:
    - vendor/bundle

lint:bundler:audit:
  <<: *lint
  script:
    - bin/bundle-audit check --update --verbose

lint:rubocop:
  <<: *lint
  script:
    - bin/rubocop

pages:
  <<: *deploy
  artifacts:
    expire_in: 1 month
    paths:
      - public
  script:
    - bin/codeclimate-test-reporter
    - mkdir -pv public
    - mv -v coverage public

stages:
  - lint
  - test
  - deploy

test:jruby:9.1:
  <<: *use_jruby
  allow_failure: true

test:mri:2.1:
  <<: *use_mri
  image: ruby:2.1

test:mri:2.2:
  <<: *use_mri
  image: ruby:2.2

test:mri:2.3:
  <<: *use_mri
  image: ruby:2.3

variables:
  JRUBY_OPTS: --debug
  LC_ALL: C.UTF-8
  RAILS_ENV: test
