addons:
  apt:
    packages:
    - texlive-latex-base
    - uuid-runtime
bundler_args: --clean --deployment --jobs=3 --retry=3 --without development production
cache: bundler
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
script:
  - bin/rake
sudo: false
